pipeline:
  publish:
    image: plugins/docker
    registry: registry.u-strasbg.fr
    repo: registry.u-strasbg.fr/seiscomp3
    tags:
      - ${DRONE_COMMIT_SHA:0:7}
      - latest
    when:
      branch: master